[package]
name = "learn-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
wgpu = "0.16"
log = "0.4"
env_logger = "0.10"
pollster = "0.3"
bytemuck = { version = "1.13", features = [ "derive" ] }